site_name: SiberianCMS Documentation
pages:
  - Home: index.md
  - Getting started: documentation.md
  - Customization:
    - 'Layouts': 'layout.md'
    - 'Icons': 'customization/icon.md'
  - Modules:
    - 'Structure & Basics': 'module.md'
    - 'Basic usage': 'module/basic.md'
    - 'Hooks': 'module/hooks.md'
    - 'Forms': 'module/forms.md'
    - 'Offline Mode': 'module/offline-mode.md'
    - 'Utils': 'module/utils.md'
    - 'Core inheritance': 'module/core-inheritance.md'
    - 'Siberian CLI': 'cli/siberian.md'
  - Stack:
    - 'Ionic tools': 'stack/ionic-tools.md'
    - 'Utilities': 'stack/utilities.md'
    - 'Frameworks': 'stack/frameworks.md'
  - API:
    - 'Introduction': 'api.md'
    - 'Application': 'api/application.md'
    - 'User': 'api/user.md'
    - 'Backoffice': 'api/backoffice.md'
    - 'Push': 'api/push.md'
  - Contribute: contribute.md
  - Hooks:
    - 'Customer': 'module/hooks/customer.md'
    - 'Loyaty Card': 'module/hooks/loyalty-card.md'
    - 'Menus': 'module/hooks/menus.md'
theme_dir: themes/xtraball
site_dir: siberiancms
repo_url: https://github.com/Xtraball/Siberian
google_analytics: ['UA-90544135-3', 'auto']
