site_name: SiberianCMS Documentation
pages:
  - Home: index.md
  - Getting started: documentation.md
  - Customization:
    - 'Layouts': 'layout.md'
    - 'Icons': 'customization/icon.md'
  - Modules:
    - 'Structure & Basics': 'module.md'
    - 'Basic usage': 'module/basic.md'
    - 'Forms': 'module/forms.md'
    - 'Offline Mode': 'module/offline-mode.md'
    - 'Utils': 'module/utils.md'
    - 'Core inheritance': 'module/core-inheritance.md'
  - API:
    - 'Introduction': 'api.md'
    - 'Application': 'api/application.md'
    - 'User': 'api/user.md'
  - Contribute: contribute.md
theme_dir: themes/xtraball
site_dir: siberiancms
repo_url: https://github.com/Xtraball/SiberianCMS/
google_analytics: ['UA-90544135-3', 'auto']
